# Test Intersection Data.

In [1]:
import numpy as np
import pickle
from matplotlib import pyplot as plt
%matplotlib notebook

with open('Intersecciones.pkl', 'rb') as f:
    inter=pickle.load(f)
f.close()

FileNotFoundError: [Errno 2] No such file or directory: 'Intersecciones.pkl'

In [31]:

def valFunc(val):
    return val[1]

lenList = [ (i,len(inter[i])) for i in range(len(inter))]
lenList.sort(key=valFunc,reverse=True)

print(lenList)

[(132, 8875), (130, 8495), (133, 8148), (131, 7463), (134, 7351), (149, 6747), (129, 6529), (147, 6301), (145, 6202), (146, 5968), (115, 5917), (117, 5911), (135, 5657), (126, 5640), (143, 5606), (140, 5483), (120, 5420), (128, 5232), (114, 5201), (116, 5193), (150, 5193), (125, 5125), (121, 5081), (138, 5062), (139, 4980), (144, 4967), (165, 4956), (127, 4945), (151, 4890), (124, 4767), (136, 4726), (137, 4716), (113, 4706), (148, 4677), (123, 4655), (196, 4617), (141, 4609), (188, 4593), (201, 4528), (193, 4473), (166, 4293), (194, 4289), (195, 4222), (163, 4193), (187, 4191), (197, 4169), (202, 4159), (152, 4153), (164, 4149), (185, 4128), (122, 4126), (162, 4116), (191, 4112), (199, 4094), (153, 4043), (198, 4037), (200, 4010), (106, 3973), (119, 3966), (142, 3925), (174, 3876), (181, 3852), (154, 3849), (189, 3845), (173, 3810), (111, 3798), (104, 3746), (118, 3733), (178, 3719), (159, 3680), (112, 3668), (177, 3666), (192, 3666), (186, 3656), (155, 3602), (175, 3509), (158, 3467)

In [97]:
from sklearn.cluster import AgglomerativeClustering

data=inter[lenList[0][0]][:,:2]
AG = AgglomerativeClustering(distance_threshold=0.5, n_clusters=None, compute_full_tree=True).fit(data)

nLabels = max(AG.labels_)
print ("leaves       = ", AG.n_leaves_)
print ("num Features = ", AG.n_features_in_)
print("labels        = ", nLabels)


clusters=[]
for i in range(nLabels):
    leaves = [j for j in range(nLabels) if AG.labels_[j]==i]
    clusters.append(leaves)
clustersSize = [len(j) for j in clusters]

leaves       =  8875
num Features =  2
labels        =  7793


In [134]:
print(clusters)
print(clustersSize)
C=clustersSize.copy()
C.sort()
print(C)
print(max(clustersSize))
print([k for k in range(len(clustersSize)) if clusterSize[k]==11])

[[1215, 6793], [4865, 5778], [5063, 7744], [1255], [634, 923], [2258, 6420], [1908, 7447], [1010, 1089, 3027, 4548, 4569], [3935, 3938, 5678], [1252, 4559], [], [2235, 4266, 6388], [3841, 5761, 5813], [7445, 7458], [71, 192], [3498, 7266], [1202, 2886, 2887], [2412, 2464], [2262, 6363], [12, 131], [5787, 7641, 7737], [1723, 2515], [3416, 4966], [4515, 4533], [2649, 3184], [1057, 1098], [4851], [5323, 5332], [2810, 3700], [5189, 7273], [5789, 5829, 7739, 7779], [343, 3898], [1220, 4199], [4893, 7344], [7180, 7635], [5130, 7257], [2670], [1535, 2333], [2, 6, 3101], [6792, 6805], [5472, 5497, 7617], [6290, 6980], [1665, 3160], [30, 150], [5993, 6432], [6727, 6731], [5661, 6336], [1394, 1451], [4370, 6114], [573, 3494], [913, 2500], [7044, 7380], [492, 3429], [5245], [3024, 3037, 4215, 4265, 5489], [4187], [4701, 4705], [5776, 5788, 7234, 7738], [1018, 1056, 5318], [2447, 7604], [1445, 1455], [4757, 4764], [1983, 2024], [922, 2995, 7172], [4212, 4252, 5236], [5766, 6642], [681, 2960], [438

NameError: name 'clusterSize' is not defined

In [137]:
N=max(clustersSize)

idxCluster=[k for k in range(len(clustersSize)) if clustersSize[k]==N][0]
print("idxCluster = ", idxCluster)
print("\n")

#Esto lo debo hacer con las coordenadas de las lineas, no con las intersecciones de éstas.
M=np.zeros((3,3))
for i in range(N):
    v=data[clusters[idxCluster][i],:].tolist()
    print("v[%d]=" %(i), v)
    v.append(1)
    M=M+np.outer(v,v)
print("\n")
print(M)
[l,V]=np.linalg.eig(M)
print("\n")

print (l)
print (V)

    

idxCluster =  130


v[0]= [1353.6232686980627, 539.8559556786693]
v[1]= [1353.4349442379169, 539.9089219330855]
v[2]= [1353.5414012738872, 539.8789808917189]
v[3]= [1353.5557265794448, 539.9046386342972]
v[4]= [1353.8027232425516, 539.8622545915152]
v[5]= [1353.4915172079504, 539.9156568104704]
v[6]= [1353.4908034849948, 539.9157792836404]
v[7]= [1353.491559086397, 539.950889229935]
v[8]= [1353.5335051546397, 539.9206553755525]
v[9]= [1353.5787781350473, 539.9260450160773]
v[10]= [1353.4910485933503, 539.9156010230181]


[[2.01530339e+07 8.03866508e+06 1.48890353e+04]
 [8.03866508e+06 3.20647192e+06 5.93895538e+03]
 [1.48890353e+04 5.93895538e+03 1.10000000e+01]]


[2.33595167e+07 3.33056955e-02 6.08803498e-09]
[[-9.28834398e-01 -3.70495038e-01 -2.98128040e-04]
 [-3.70494522e-01  9.28833994e-01 -1.10476565e-03]
 [-6.86221649e-04  9.15689508e-04  9.99999345e-01]]
