In [1]:
import cv2
import numpy as np
import random
import matplotlib.pyplot as plt
from clipBox import *
import datetime

%matplotlib notebook

In [2]:
def null_space(A, rcond = None):
        """
        Computes the null space of a matrix.
        """
        u, s, vh = np.linalg.svd(A, full_matrices=True)
        M, N = u.shape[0], vh.shape[1]
        if rcond is None:
            rcond = np.finfo(s.dtype).eps * max(M, N)
        tol = np.amax(s) * rcond
        num = np.sum(s > tol, dtype=int)
        Q = vh[num:, :].T.conj()
        return Q
    
def norm_points(p):
    r,c = p.shape
    for i in range(c):
        if p[-1,i] != 0:
            p[:,i] /= p[-1,i]
    return p

def time_difference(start_time, end_time):
    """
    Calculates the time difference between two datetime objects in microseconds.
    """
    delta = end_time - start_time
    if delta.seconds == 0:
        return delta.microseconds
    else:
        return delta.seconds*1e6+microseconds




In [3]:
def sortPts(P):
    theta = np.zeros(4)
    mX = np.mean(P[0,: ])
    mY = np.mean(P[1, :])
    for k in range(4):
        Dx = P[0, k] - mX
        Dy = P[1, k] - mY
        theta[k] = np.arctan2(Dy, Dx)
    
    indices = sorted(range(len(theta)), key = lambda index: theta[index])
    sP = P[:, indices]
    return sP, indices

def sortPtsIdx(p,i,j):
    P = np.array([[p[i, 0, 0],p[i, 0, 2],p[j, 0, 0],p[j, 0, 2]],
                  [p[i, 0, 1],p[i, 0, 3],p[j, 0, 1],p[j, 0, 3]],
                  [  1,                1,         1,        1]]).astype('float64')
    return sortPts(P)

def line_similarity(line_a, line_b, threshold=1, normType = 0, clpB=None):
    distance = np.inf
    pts = None
    tstamps = []
    tstamps.append([0,datetime.datetime.now()])
    if normType == 1:
        # Normalize the lines as homogeneous variable
        linea_n = line_a / line_a[2]
        lineb_n = line_b / line_b[2]
        tmp = linea_n[:2] - lineb_n[:2]
        distance = np.dot(tmp, tmp)
        tstamps.append([1, datetime.datetime.now()])
    elif normType == 2:
        # Normalize the lines according to their size
        lineb_n = line_b / np.linalg.norm(line_b)
        linea_n = line_a / np.linalg.norm(line_a)
        tmp = lineb_n - linea_n
        distance = np.dot(tmp, tmp)
        tstamps.append([2, datetime.datetime.now()])
    else:
        if clpB == None:
            clpB = clipBox((0,540),(1920,540))
        pl1, pl2, success = clpB.clipLine(line_a)
        if success == True:
            tstamps.append([2, datetime.datetime.now()])
            pl3, pl4, success = clpB.clipLine(line_b)
            if success == True:
                tstamps.append([3, datetime.datetime.now()])
                P = np.hstack([pl1,pl2,pl3,pl4]).reshape(4,3).transpose()
                tstamps.append([4, datetime.datetime.now()])
                sP, idx = sortPts(P)
                tstamps.append([5, datetime.datetime.now()])
                d=[]
                tmp = sP[:2,0]-sP[:2,1]
                d.append(np.dot(tmp, tmp)) #Squared Distance between P[0,:] and P[1,:]
                tmp = sP[:2,2]-sP[:2,3]
                d.append(np.dot(tmp, tmp)) #Squared Distance between P[0,:] and P[1,:]
                pts = P.copy()
                tstamps.append([6, datetime.datetime.now()])
                if d[0] > d[1]:
                    distance = d[0]
                    pts = np.hstack([pts, np.array(sP[:,0],ndmin=2).transpose()])
                    pts = np.hstack([pts, np.array(sP[:,1],ndmin=2).transpose()])
                else:
                    distance = d[1]
                    pts = np.hstack([pts, np.array(sP[:,2],ndmin=2).transpose()])
                    pts = np.hstack([pts, np.array(sP[:,3],ndmin=2).transpose()])
                tstamps.append([7, datetime.datetime.now()])

    # Compute similarity
    tstamps.append([8, datetime.datetime.now()])
    
    for i in range(1,len(tstamps)):
        tstamps[i][1] = time_difference(tstamps[0][1],tstamps[i][1])
    return distance <= (threshold * threshold), distance, pts, tstamps

In [4]:
def select_lines_with_distance(lines_vp1, clpBox, threshold_min, threshold_max, max_attempts=1000):
    """
    Select two random lines with distance between thresholds.

    Args:
        lines_vp1: List of lines, each as (x1, y1, x2, y2)
        img_width: Image width for line extension
        img_height: Image height for line extension
        threshold_min: Minimum allowed distance between lines
        threshold_max: Maximum allowed distance between lines
        max_attempts: Maximum attempts before giving up

    Returns:
        Tuple of (idx1, idx2, distance) for the selected lines

    Raises:
        ValueError if no suitable pair is found
    """
    n = len(lines_vp1)
    if n < 2:
        raise ValueError("Need at least 2 lines to select a pair")

    threshold_min *= threshold_min
    threshold_max *= threshold_max
        
    print ("Select_Lines_with_distance", flush=True)
    for intento in range(max_attempts):
        print("Intento  #%d" % intento, flush = True)
        # Select two distinct random indices
        idx1, idx2 = random.sample(range(n), 2)
        
        line1 = lines_vp1[idx1][0]
        M = np.array([[line1[0], line1[1], 1], [line1[2], line1[3], 1]])
        l1 = null_space(M)[:, 0]
        l1 /= l1[2]
        
        line2 = lines_vp1[idx2][0]
        M = np.array([[line2[0], line2[1], 1], [line2[2], line2[3], 1]])
        l1 = null_space(M)[:, 0]
        l1 /= l1[2]
        
        # Calculate distance between extended lines
        start_time = datetime.datetime.now()
        _, distance, _, tstamps = line_similarity(l1, l2, threshold=1, normType = 0, clpB=clpBox)
        print("Timestamps: ", tstamps[1:])
        end_time = datetime.datetime.now()
        print("Antes de line_similarity", start_time, flush=True)
        print("Despues de line_similarity:", end_time,flush=True)
        
        print ("La distancia al cuadrado entre l1 y l2 es:", distance, flush=True)
        print ("Y me costó %f microsegundos calcularlo" % time_difference(start_time, end_time), "\n", flush=True)
        
        # Check if distance is within desired range
        if threshold_min <= distance <= threshold_max:
            return idx1, idx2, distance

    raise ValueError(f"No valid line pair found after {max_attempts} attempts")

In [5]:
def line_passes_near_vp(line, vp, threshold=10):
    x1, y1, x2, y2 = line
    line_params = np.polyfit([x1, x2], [y1, y2], 1)
    slope, intercept = line_params
    vp_x, vp_y = vp[0], vp[1]
    return abs(vp_y - (slope * vp_x + intercept)) < threshold

def def_grid_lines(r0,r1,c0,c1,w,h):
    R=np.linspace(r0,r1,r1-r0+1)
    C=np.linspace(c0,c1,c1-c0+1)
    n = len(R)+len(C)
    l=np.zeros((3, n))
    
    #Definimos primero lineas horizontales
    idx=0
    for i in R:
        l[:,idx]=[0, 1, h*i]
        idx +=1
        
    #Definimos primero lineas verticales
    for i in C:
        l[:,idx]=[1, 0, h*i]
        idx=idx+1
    return l

In [6]:
# Definir puntos de fuga y puntos
vp1 = np.array([-3, 540, 1])
vp2 = np.array([1916, 540, 1])

# Load data
lines_near_vps = np.load('merged_lines_near_vps.npy')

clpBox = clipBox((0,0),(1920,1080))

lines_vp1 = []
lines_vp2 = []

img = cv2.imread('vp.jpg')
cv2.circle(img, (vp1[0], vp1[1]), 5, (0, 255, 0), -1)
cv2.circle(img, (vp2[0], vp2[1]), 5, (0, 255, 0), -1)

for line in lines_near_vps:
    if line_passes_near_vp(line[0], vp1):
        lines_vp1.append(line)
    elif line_passes_near_vp(line[0], vp2):
        lines_vp2.append(line)

# Draw lines passing through vp1
for line in lines_vp1:
    x1, y1, x2, y2 = line[0]
    M = np.array([[x1, y1, 1], [x2, y2, 1]])
    l1 = null_space(M)[:, 0]
   
    pt1, pt2, success = clpBox.clipLine(l1)
    if success:
        pt1 /= pt1[2]
        pt2 /= pt2[2]
        
        pt1=tuple(np.round(pt1[:2]).astype('int64'))
        pt2=tuple(np.round(pt2[:2]).astype('int64'))
   
        cv2.line(img, pt1, pt2, (255, 0, 0), 1)  # Blue color for lines passing through vp1

# Draw lines passing through vp2
for line in lines_vp2:
    x1, y1, x2, y2 = line[0]
    M = np.array([[x1, y1, 1], [x2, y2, 1]])
    l2 = np.array(null_space(M)[:, 0])
    pt1, pt2, success = clpBox.clipLine(l2)
    if success:
        pt1 /= pt1[2]
        pt2 /= pt2[2]
    
        pt1=tuple(np.round(pt1[:2]).astype('int64'))
        pt2=tuple(np.round(pt2[:2]).astype('int64'))
   
        cv2.line(img, pt1, pt2[:2], (0, 0, 255), 1)  # Red color for lines passing through vp2
    
# Display the image with the drawn lines
cv2.namedWindow("Image with Lines", cv2.WINDOW_NORMAL)
cv2.imshow('Image with Lines', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

QSettings::value: Empty key passed
QSettings::value: Empty key passed


In [7]:
tuple(pt1[:2])

(1920, 534)

In [15]:
def points_to_homogeneous_line(x1, y1, x2, y2):
    return np.cross([x1, y1, 1], [x2, y2, 1])

def order_lines_by_intersection(lines, horizon_y=540, offset=10):
    H10 = np.array([0, 1, -(horizon_y + offset)])  # Línea horizontal

    intersections = []
    for line in lines:
        intersection = np.cross(line, H10)
        intersection = intersection / intersection[-1]  # Normalizar
        intersections.append(intersection)

    # Ordenar las líneas según la coordenada x de las intersecciones
    sorted_indices = np.argsort([pt[0] for pt in intersections])  # Ordenar por x
    ordered_lines = [lines[i] for i in sorted_indices]
    return ordered_lines

In [20]:
def main_process(lines_near_vps, vp1, vp2, thr=1, iterations=100, grid_size=5, region=[1920, 1080]):
    results = []
    
    lines_vp1 = []
    lines_vp2 = []


    for line in lines_near_vps:
     
        if line_passes_near_vp(line[0], vp1):
            lines_vp1.append(line)
        elif line_passes_near_vp(line[0], vp2):
            lines_vp2.append(line)
   

    #Define Grid Lines
    grid_lines = def_grid_lines(-grid_size, grid_size, -grid_size, grid_size, 1, 1)
    clpBox = clipBox((0,0), (region[0], region[1]))
    
    # Define the square of 1x1
    pr = np.ones((3,4))
    pr[:2,0] = [0., 1]
    pr[:2,1] = [0., 0.]
    pr[:2,2] = [1, 0.]
    pr[:2,3] = [1, 1.]
    pr = norm_points(pr)
    src_pts = np.float32([pr[:, 0], pr[:, 1], pr[:, 2], pr[:, 3]])
    
    for it in range(iterations):
        print ("Iteracion: ", it, flush=True)
        # Step 1: Select random lines
        
        # Select two random lines from lines_vp1
        print ("Step 1.1: Select lines from VP1", flush=True)
        idx1, idx2, distance = select_lines_with_distance(lines_vp1, clpBox, 50, 2000)
        random_lines_vp1 = [lines_vp1[idx1], lines_vp1[idx2]]
        
        # Select two random lines from lines_vp2
        print ("Step 1.2: Select lines from VP2", flush=True)
        idx1, idx2, distance = select_lines_with_distance(lines_vp2, clpBox, 50, 2000)
        random_lines_vp2 = [lines_vp2[idx1], lines_vp2[idx2]]
        
        homogeneous_lines = [points_to_homogeneous_line(*line[0]) for line in random_lines_vp1 + random_lines_vp2]
        # print(homogeneous_lines)
        
        # Step 2: Find intersections
        print("Step 2:ordered_lines_by_intersection", flush=True)
        ordered_lines = order_lines_by_intersection(homogeneous_lines)

        l1 = ordered_lines[1]
        l2 = ordered_lines[0]
        l3 = ordered_lines[2]
        l4 = ordered_lines[3]

        p1 = np.cross(l2, l3)
        p2 = np.cross(l1, l3)
        p3 = np.cross(l1, l4)
        p4 = np.cross(l2, l4)

        p = np.zeros((3, 4))
        p[:, 0] = p1
        p[:, 1] = p2
        p[:, 2] = p3
        p[:, 3] = p4
        p = norm_points(p)

        #Step 3 Compute homography M
        print("Step 3:Compute Homography", flush=True)
        
        dst_pts = np.float32([p[:, 0], p[:, 1], p[:, 2], p[:, 3]])
        M, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC)  

        try:
            Hl = np.linalg.inv(M).T
        except np.linalg.LinAlgError:
            continue

        projected_lines = np.dot(Hl, grid_lines)
        print ("Projected Lines Antes:", projected_lines, flush=True)
        projected_lines = projected_lines / np.linalg.norm(projected_lines, axis=0)
        print ("Projected Lines Despues:", projected_lines, flush=True)

        # Step 4: Compare lines
        similarities = 0
        Dist = 0
        clp = clipBox((0,region[1]//2),(region[0], region[1]//2))
        cont = 0
        print ("Step 4: Compara Lineas", flush=True)
        print ("projected_lines.shape = ", projected_lines.shape,flush=True)
        print ("len(lines_near_vps)   = ", len(lines_near_vps), flush=True)
        for line in projected_lines.T:
            for original_line in lines_near_vps:
                cont+=1
                original_line =original_line[0]
                homogeneous_line = points_to_homogeneous_line(original_line[0], original_line[1], original_line[2], original_line[3])

                isSimil,d,_,_ = line_similarity(line, homogeneous_line, threshold = thr, normType = 0, clpB = clp)
                #isSimil,d,_ = line_similarity_old(line, homogeneous_line, 0.2)
                if isSimil:
                    similarities += 1
                    Dist += d
                    break
        print("Se requirieron ", cont, " iteraciones para buscar similitudes.", flush=True)

        # Step 5: Save results
        results.append((similarities, Dist/similarities, M, it))

    # Step 6: Rank results
    results.sort(key=lambda x: x[0], reverse=True)
    return results

In [21]:
# Run the process
best_results = main_process(lines_near_vps, vp1, vp2, thr=2, iterations=100, grid_size=5, region=(1920,1080))

Iteracion:  0
Step 1.1: Select lines from VP1
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 340], [3, 523], [4, 545], [5, 615], [6, 636], [7, 661], [8, 663]]
Antes de line_similarity 2025-05-18 17:23:37.329968
Despues de line_similarity: 2025-05-18 17:23:37.330681
La distancia al cuadrado entre l1 y l2 es: 3805207.143698069
Y me costó 713.000000 microsegundos calcularlo 

Step 1.2: Select lines from VP2
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 253], [3, 429], [4, 451], [5, 521], [6, 561], [7, 593], [8, 595]]
Antes de line_similarity 2025-05-18 17:23:37.332815
Despues de line_similarity: 2025-05-18 17:23:37.333937
La distancia al cuadrado entre l1 y l2 es: 71432.93033312286
Y me costó 1122.000000 microsegundos calcularlo 

Step 2:ordered_lines_by_intersection
Step 3:Compute Homography
Projected Lines Antes: [[-1.09247154e-03 -1.04625623e-03 -1.00004093e-03 -9.53825624e-04
  -9.07610320e-04 -8.61395015e-04 -8.15179711e-04 -7.68964406e-04
  -7.22749101e-04 -6.76

Projected Lines Despues: [[-1.89993042e-04 -2.01828946e-04 -2.14269543e-04 -2.27362387e-04
  -2.41160154e-04 -2.55721350e-04 -2.71111137e-04 -2.87402312e-04
  -3.04676456e-04 -3.23025302e-04 -3.42552362e-04  2.92725556e-04
   2.94710755e-04  2.98113765e-04  3.05297111e-04  3.30430423e-04
  -1.03759490e-04 -2.54991283e-04 -2.68716241e-04 -2.73862097e-04
  -2.76557327e-04 -2.78215856e-04]
 [ 1.73972986e-03  1.76212088e-03  1.78565584e-03  1.81042472e-03
   1.83652716e-03  1.86407385e-03  1.89318805e-03  1.92400749e-03
   1.95668649e-03  1.99139859e-03  2.02833963e-03  8.14277463e-04
   8.07298366e-04  7.95334866e-04  7.70081348e-04  6.81723548e-04
  -1.47859943e-03 -9.46934720e-04 -8.98683754e-04 -8.80593167e-04
  -8.71117913e-04 -8.65287249e-04]
 [-9.99998469e-01 -9.99998427e-01 -9.99998383e-01 -9.99998335e-01
  -9.99998285e-01 -9.99998230e-01 -9.99998171e-01 -9.99998108e-01
  -9.99998039e-01 -9.99997965e-01 -9.99997884e-01 -9.99999626e-01
  -9.99999631e-01 -9.99999639e-01 -9.99999657e-

Despues de line_similarity: 2025-05-18 17:23:38.113402
La distancia al cuadrado entre l1 y l2 es: 657132.0896697482
Y me costó 1156.000000 microsegundos calcularlo 

Step 2:ordered_lines_by_intersection
Step 3:Compute Homography
Projected Lines Antes: [[-9.86642275e-04 -9.74985161e-04 -9.63328046e-04 -9.51670932e-04
  -9.40013818e-04 -9.28356703e-04 -9.16699589e-04 -9.05042474e-04
  -8.93385360e-04 -8.81728245e-04 -8.70071131e-04  2.20169649e-03
   2.21335360e-03  2.22501072e-03  2.23666783e-03  2.24832494e-03
   2.25998206e-03  2.27163917e-03  2.28329629e-03  2.29495340e-03
   2.30661052e-03  2.31826763e-03]
 [-1.03479785e-01 -7.59140037e-02 -4.83482219e-02 -2.07824402e-02
   6.78334161e-03  3.43491234e-02  6.19149051e-02  8.94806869e-02
   1.17046469e-01  1.44612250e-01  1.72178032e-01 -1.05624178e-01
  -7.80583966e-02 -5.04926149e-02 -2.29268331e-02  4.63894866e-03
   3.22047304e-02  5.97705122e-02  8.73362939e-02  1.14902076e-01
   1.42467857e-01  1.70033639e-01]
 [ 5.62808385e+01 

Projected Lines Despues: [[-5.15595188e-04 -4.30558055e-04 -3.70373398e-04 -3.25535407e-04
  -2.90837912e-04 -2.63190352e-04 -2.40642240e-04 -2.21901853e-04
  -2.06079768e-04 -1.92543557e-04 -1.80831222e-04  1.62768805e-04
   2.60529392e-04  7.70990102e-04  6.58575569e-04  2.14826801e-04
   1.22389105e-04  8.23798442e-05  6.00493802e-05  4.58005250e-05
   3.59183036e-05  2.86621528e-05]
 [ 1.80777644e-03  1.82327429e-03  1.83424281e-03  1.84241443e-03
   1.84873796e-03  1.85377666e-03  1.85788600e-03  1.86130139e-03
   1.86418492e-03  1.86665186e-03  1.86878641e-03 -2.39479564e-03
  -2.73166182e-03 -4.49061804e-03 -4.35424842e-04  1.09366395e-03
   1.41218919e-03  1.55005453e-03  1.62700162e-03  1.67610082e-03
   1.71015331e-03  1.73515680e-03]
 [-9.99998233e-01 -9.99998245e-01 -9.99998249e-01 -9.99998250e-01
  -9.99998249e-01 -9.99998247e-01 -9.99998245e-01 -9.99998243e-01
  -9.99998241e-01 -9.99998239e-01 -9.99998237e-01  9.99997119e-01
   9.99996235e-01  9.99989620e-01 -9.99999688e-

Step 4: Compara Lineas
projected_lines.shape =  (3, 22)
len(lines_near_vps)   =  37
Se requirieron  742  iteraciones para buscar similitudes.
Iteracion:  10
Step 1.1: Select lines from VP1
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 92], [3, 161], [4, 173], [5, 208], [6, 217], [7, 642], [8, 643]]
Antes de line_similarity 2025-05-18 17:23:38.892113
Despues de line_similarity: 2025-05-18 17:23:38.892778
La distancia al cuadrado entre l1 y l2 es: 3695444.9958195467
Y me costó 665.000000 microsegundos calcularlo 

Step 1.2: Select lines from VP2
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 102], [3, 167], [4, 177], [5, 208], [6, 215], [7, 227], [8, 227]]
Antes de line_similarity 2025-05-18 17:23:38.894883
Despues de line_similarity: 2025-05-18 17:23:38.895130
La distancia al cuadrado entre l1 y l2 es: 909772.4939062493
Y me costó 247.000000 microsegundos calcularlo 

Step 2:ordered_lines_by_intersection
Step 3:Compute Homography
Projected Lines Antes: [[ 9.46820207

Projected Lines Despues: [[-6.79682392e-04 -4.96379966e-04 -3.96634365e-04 -3.33917355e-04
  -2.90837794e-04 -2.59421072e-04 -2.35495679e-04 -2.16667579e-04
  -2.01464627e-04 -1.88931790e-04 -1.78422420e-04  6.32616934e-03
   1.20038117e-03  5.13366564e-04  3.11402340e-04  2.14826814e-04
   1.58218423e-04  1.21020580e-04  9.47108472e-05  7.51189986e-05
   5.99633362e-05  4.78903662e-05]
 [ 1.56034242e-03  1.69629286e-03  1.77027142e-03  1.81678688e-03
   1.84873779e-03  1.87203869e-03  1.88978347e-03  1.90374774e-03
   1.91502334e-03  1.92431859e-03  1.93211309e-03 -2.32622367e-02
  -2.24663544e-03  8.18376048e-05  7.66345396e-04  1.09366393e-03
   1.28552378e-03  1.41159644e-03  1.50076659e-03  1.56716817e-03
   1.61853442e-03  1.65945267e-03]
 [-9.99998552e-01 -9.99998438e-01 -9.99998354e-01 -9.99998294e-01
  -9.99998249e-01 -9.99998214e-01 -9.99998187e-01 -9.99998164e-01
  -9.99998146e-01 -9.99998131e-01 -9.99998118e-01  9.99709382e-01
  -9.99996756e-01 -9.99999865e-01 -9.99999658e-

len(lines_near_vps)   =  37
Se requirieron  752  iteraciones para buscar similitudes.
Iteracion:  15
Step 1.1: Select lines from VP1
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 192], [3, 365], [4, 385], [5, 453], [6, 475], [7, 508], [8, 512]]
Antes de line_similarity 2025-05-18 17:23:39.635817
Despues de line_similarity: 2025-05-18 17:23:39.636376
La distancia al cuadrado entre l1 y l2 es: 3805207.143698069
Y me costó 559.000000 microsegundos calcularlo 

Step 1.2: Select lines from VP2
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 202], [3, 371], [4, 390], [5, 454], [6, 769], [7, 796], [8, 797]]
Antes de line_similarity 2025-05-18 17:23:39.638950
Despues de line_similarity: 2025-05-18 17:23:39.639793
La distancia al cuadrado entre l1 y l2 es: 24672.080950085485
Y me costó 843.000000 microsegundos calcularlo 

Step 2:ordered_lines_by_intersection
Step 3:Compute Homography
Projected Lines Antes: [[-4.34530061e-04 -5.19965703e-04 -6.05401346e-04 -6.90836988e-04
  

Projected Lines Despues: [[-7.02753101e-04 -5.11826901e-04 -4.06359191e-04 -3.39465852e-04
  -2.93256019e-04 -2.59421148e-04 -2.33577245e-04 -2.13192392e-04
  -1.96702134e-04 -1.83087680e-04 -1.71657081e-04  1.80128643e-04
   2.52221463e-04  4.78383335e-04  6.34454930e-03  3.44461202e-04
   1.57929983e-04  9.31493365e-05  6.02477316e-05  4.03400505e-05
   2.69980626e-05  1.74334531e-05]
 [ 1.60979063e-03  1.72273099e-03  1.78511925e-03  1.82468925e-03
   1.85202414e-03  1.87203877e-03  1.88732643e-03  1.89938485e-03
   1.90913947e-03  1.91719294e-03  1.92395458e-03 -2.50022700e-03
  -2.75785433e-03 -3.56605432e-03 -2.08165890e-02  6.25574725e-04
   1.29215567e-03  1.52365315e-03  1.64122894e-03  1.71237017e-03
   1.76004853e-03  1.79422820e-03]
 [-9.99998457e-01 -9.99998385e-01 -9.99998324e-01 -9.99998278e-01
  -9.99998242e-01 -9.99998214e-01 -9.99998192e-01 -9.99998173e-01
  -9.99998158e-01 -9.99998145e-01 -9.99998134e-01  9.99996858e-01
   9.99996165e-01  9.99993527e-01 -9.99763180e-

Step 4: Compara Lineas
projected_lines.shape =  (3, 22)
len(lines_near_vps)   =  37
Se requirieron  756  iteraciones para buscar similitudes.
Iteracion:  20
Step 1.1: Select lines from VP1
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 258], [3, 508], [4, 538], [5, 627], [6, 923], [7, 961], [8, 963]]
Antes de line_similarity 2025-05-18 17:23:40.449718
Despues de line_similarity: 2025-05-18 17:23:40.450741
La distancia al cuadrado entre l1 y l2 es: 3695444.9958195467
Y me costó 1023.000000 microsegundos calcularlo 

Step 1.2: Select lines from VP2
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 133], [3, 211], [4, 227], [5, 275], [6, 288], [7, 305], [8, 306]]
Antes de line_similarity 2025-05-18 17:23:40.453459
Despues de line_similarity: 2025-05-18 17:23:40.454457
La distancia al cuadrado entre l1 y l2 es: 158.42682546954876
Y me costó 998.000000 microsegundos calcularlo 

Intento  #1
Timestamps:  [[2, 95], [3, 168], [4, 180], [5, 225], [6, 235], [7, 250], [8, 250]]
A

Y me costó 621.000000 microsegundos calcularlo 

Step 2:ordered_lines_by_intersection
Step 3:Compute Homography
Projected Lines Antes: [[-5.15472890e-03 -5.27997582e-03 -5.40522274e-03 -5.53046966e-03
  -5.65571658e-03 -5.78096350e-03 -5.90621042e-03 -6.03145734e-03
  -6.15670426e-03 -6.28195118e-03 -6.40719810e-03  2.40639244e-03
   2.28114552e-03  2.15589860e-03  2.03065168e-03  1.90540476e-03
   1.78015784e-03  1.65491092e-03  1.52966400e-03  1.40441708e-03
   1.27917016e-03  1.15392324e-03]
 [ 1.28885528e-02  1.86541796e-02  2.44198063e-02  3.01854331e-02
   3.59510599e-02  4.17166867e-02  4.74823134e-02  5.32479402e-02
   5.90135670e-02  6.47791938e-02  7.05448205e-02 -1.96021106e-02
  -1.38364838e-02 -8.07085704e-03 -2.30523026e-03  3.46039651e-03
   9.22602329e-03  1.49916501e-02  2.07572768e-02  2.65229036e-02
   3.22885304e-02  3.80541572e-02]
 [-8.09494786e+00 -1.09327695e+01 -1.37705911e+01 -1.66084127e+01
  -1.94462343e+01 -2.22840559e+01 -2.51218775e+01 -2.79596991e+01
  -

La distancia al cuadrado entre l1 y l2 es: 906947.3087351547
Y me costó 774.000000 microsegundos calcularlo 

Step 2:ordered_lines_by_intersection
Step 3:Compute Homography
Projected Lines Antes: [[ 1.49659228e-02  1.52471604e-02  1.55283980e-02  1.58096356e-02
   1.60908731e-02  1.63721107e-02  1.66533483e-02  1.69345859e-02
   1.72158235e-02  1.74970610e-02  1.77782986e-02  5.57023461e-04
   8.38261044e-04  1.11949863e-03  1.40073621e-03  1.68197379e-03
   1.96321137e-03  2.24444896e-03  2.52568654e-03  2.80692412e-03
   3.08816170e-03  3.36939928e-03]
 [-1.30763658e-01 -1.23643506e-01 -1.16523354e-01 -1.09403202e-01
  -1.02283050e-01 -9.51628984e-02 -8.80427464e-02 -8.09225944e-02
  -7.38024424e-02 -6.66822905e-02 -5.95621385e-02 -2.54259857e-02
  -1.83058337e-02 -1.11856817e-02 -4.06552977e-03  3.05462220e-03
   1.01747742e-02  1.72949262e-02  2.44150781e-02  3.15352301e-02
   3.86553821e-02  4.57755340e-02]
 [ 7.27142196e+01  6.83671078e+01  6.40199961e+01  5.96728843e+01
   5.532

Projected Lines Despues: [[-3.89039373e-03 -1.74287560e-03 -7.14126672e-04 -4.49916409e-04
  -3.28864469e-04 -2.59421045e-04 -2.14381577e-04 -1.82804486e-04
  -1.59438662e-04 -1.41449755e-04 -1.27173283e-04  1.06719825e-04
   1.57461706e-04  3.05577012e-04  7.46872753e-03  3.26050191e-04
   1.57929841e-04  1.03489184e-04  7.65591620e-05  6.04928614e-05
   4.98199372e-05  4.22149196e-05]
 [-1.75451654e-03  1.91404203e-03  1.88491387e-03  1.87743266e-03
   1.87400498e-03  1.87203863e-03  1.87076329e-03  1.86986915e-03
   1.86920752e-03  1.86869815e-03  1.86829389e-03 -2.23328780e-03
  -2.41373296e-03 -2.94045114e-03 -2.84129263e-02  6.94295019e-04
   1.29215587e-03  1.48575475e-03  1.58152179e-03  1.63865586e-03
   1.67661031e-03  1.70365484e-03]
 [ 9.99990893e-01 -9.99996649e-01 -9.99997969e-01 -9.99998136e-01
  -9.99998190e-01 -9.99998214e-01 -9.99998227e-01 -9.99998235e-01
  -9.99998240e-01 -9.99998244e-01 -9.99998247e-01  9.99997501e-01
   9.99997075e-01  9.99995630e-01  9.99568369e-

Despues de line_similarity: 2025-05-18 17:23:41.981552
La distancia al cuadrado entre l1 y l2 es: 160.50881404290877
Y me costó 286.000000 microsegundos calcularlo 

Intento  #1
Timestamps:  [[2, 82], [3, 146], [4, 154], [5, 183], [6, 192], [7, 203], [8, 203]]
Antes de line_similarity 2025-05-18 17:23:41.982760
Despues de line_similarity: 2025-05-18 17:23:41.982983
La distancia al cuadrado entre l1 y l2 es: 145.50390625001646
Y me costó 223.000000 microsegundos calcularlo 

Intento  #2
Timestamps:  [[2, 74], [3, 132], [4, 139], [5, 163], [6, 1589], [7, 1654], [8, 1656]]
Antes de line_similarity 2025-05-18 17:23:41.984204
Despues de line_similarity: 2025-05-18 17:23:41.986050
La distancia al cuadrado entre l1 y l2 es: 181.15074946645768
Y me costó 1846.000000 microsegundos calcularlo 

Intento  #3
Timestamps:  [[2, 230], [3, 430], [4, 454], [5, 550], [6, 965], [7, 1004], [8, 1005]]
Antes de line_similarity 2025-05-18 17:23:41.987668
Despues de line_similarity: 2025-05-18 17:23:41.988748

Projected Lines Despues: [[ 2.05836565e-04  2.23031073e-04  2.42562058e-04  2.64940475e-04
   2.90837976e-04  3.21155480e-04  3.57130121e-04  4.00508231e-04
   4.53837366e-04  5.20985346e-04  6.08122836e-04  6.16000921e-05
   1.35769324e-04  4.22076757e-04  1.19557769e-03  3.25968395e-04
   2.12294017e-04  1.67497562e-04  1.43533039e-04  1.28610456e-04
   1.18424638e-04  1.11029168e-04]
 [-1.79833090e-03 -1.80852750e-03 -1.82010966e-03 -1.83338039e-03
  -1.84873799e-03 -1.86671671e-03 -1.88805019e-03 -1.91377404e-03
  -1.94539897e-03 -1.98521868e-03 -2.03689243e-03 -2.09504862e-03
  -2.36398497e-03 -3.40212939e-03 -2.46347836e-03  6.89729638e-04
   1.10191207e-03  1.26434358e-03  1.35123868e-03  1.40534781e-03
   1.44228147e-03  1.46909735e-03]
 [ 9.99998362e-01  9.99998340e-01  9.99998314e-01  9.99998284e-01
   9.99998249e-01  9.99998206e-01  9.99998154e-01  9.99998089e-01
   9.99998005e-01  9.99997894e-01  9.99997741e-01  9.99997803e-01
   9.99997197e-01  9.99994124e-01 -9.99996251e-

Despues de line_similarity: 2025-05-18 17:23:42.865209
La distancia al cuadrado entre l1 y l2 es: 3702283.9732230464
Y me costó 297.000000 microsegundos calcularlo 

Step 1.2: Select lines from VP2
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 275], [3, 481], [4, 504], [5, 584], [6, 776], [7, 806], [8, 807]]
Antes de line_similarity 2025-05-18 17:23:42.867976
Despues de line_similarity: 2025-05-18 17:23:42.868841
La distancia al cuadrado entre l1 y l2 es: 632554.573376954
Y me costó 865.000000 microsegundos calcularlo 

Step 2:ordered_lines_by_intersection
Step 3:Compute Homography
Projected Lines Antes: [[-1.60988153e-02 -1.62281717e-02 -1.63575281e-02 -1.64868845e-02
  -1.66162409e-02 -1.67455974e-02 -1.68749538e-02 -1.70043102e-02
  -1.71336666e-02 -1.72630230e-02 -1.73923794e-02  2.82092832e-03
   2.69157191e-03  2.56221550e-03  2.43285909e-03  2.30350268e-03
   2.17414627e-03  2.04478986e-03  1.91543345e-03  1.78607703e-03
   1.65672062e-03  1.52736421e-03]
 [ 9.6914625

Projected Lines Despues: [[-6.14708092e-04 -4.80677731e-04 -3.95454089e-04 -3.36484242e-04
  -2.93255868e-04 -2.60208110e-04 -2.34123425e-04 -2.13010902e-04
  -1.95572585e-04 -1.80926121e-04 -1.68450744e-04 -7.28262818e-05
  -8.49375132e-05 -1.01049901e-04 -1.23538553e-04 -1.57122122e-04
  -2.12699825e-04 -3.22397597e-04 -6.40276491e-04 -1.27495285e-02
  -7.39823019e-04 -3.66150930e-04]
 [ 1.88385167e-03  1.87058101e-03  1.86214280e-03  1.85630404e-03
   1.85202388e-03  1.84875172e-03  1.84616900e-03  1.84407859e-03
   1.84235197e-03  1.84090178e-03  1.83966656e-03 -1.55051264e-03
  -1.51170793e-03 -1.46008339e-03 -1.38802913e-03 -1.28042643e-03
  -1.10235385e-03 -7.50878811e-04  2.67616317e-04  3.90675973e-02
   4.15425620e-03  2.95700548e-03]
 [-9.99998037e-01 -9.99998135e-01 -9.99998188e-01 -9.99998220e-01
  -9.99998242e-01 -9.99998257e-01 -9.99998268e-01 -9.99998277e-01
  -9.99998284e-01 -9.99998289e-01 -9.99998294e-01  9.99998795e-01
   9.99998854e-01  9.99998929e-01  9.99999029e-

len(lines_near_vps)   =  37
Se requirieron  764  iteraciones para buscar similitudes.
Iteracion:  39
Step 1.1: Select lines from VP1
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 85], [3, 150], [4, 159], [5, 185], [6, 191], [7, 203], [8, 203]]
Antes de line_similarity 2025-05-18 17:23:43.714734
Despues de line_similarity: 2025-05-18 17:23:43.714957
La distancia al cuadrado entre l1 y l2 es: 3695444.9958195467
Y me costó 223.000000 microsegundos calcularlo 

Step 1.2: Select lines from VP2
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 469], [3, 637], [4, 660], [5, 731], [6, 749], [7, 773], [8, 774]]
Antes de line_similarity 2025-05-18 17:23:43.718211
Despues de line_similarity: 2025-05-18 17:23:43.719047
La distancia al cuadrado entre l1 y l2 es: 561.943957270288
Y me costó 836.000000 microsegundos calcularlo 

Intento  #1
Timestamps:  [[2, 132], [3, 219], [4, 243], [5, 319], [6, 339], [7, 355], [8, 355]]
Antes de line_similarity 2025-05-18 17:23:43.720956
Despues 

Timestamps:  [[2, 107], [3, 182], [4, 194], [5, 233], [6, 243], [7, 257], [8, 258]]
Antes de line_similarity 2025-05-18 17:23:44.034867
Despues de line_similarity: 2025-05-18 17:23:44.035155
La distancia al cuadrado entre l1 y l2 es: 561.943957270288
Y me costó 288.000000 microsegundos calcularlo 

Intento  #1
Timestamps:  [[2, 257], [3, 447], [4, 479], [5, 584], [6, 609], [7, 642], [8, 644]]
Antes de line_similarity 2025-05-18 17:23:44.037043
Despues de line_similarity: 2025-05-18 17:23:44.037768
La distancia al cuadrado entre l1 y l2 es: 27006.15015162384
Y me costó 725.000000 microsegundos calcularlo 

Step 2:ordered_lines_by_intersection
Step 3:Compute Homography
Projected Lines Antes: [[-1.13973455e-03 -1.05088173e-03 -9.62028902e-04 -8.73176079e-04
  -7.84323255e-04 -6.95470432e-04 -6.06617608e-04 -5.17764785e-04
  -4.28911961e-04 -3.40059138e-04 -2.51206315e-04  6.74157658e-03
   6.83042940e-03  6.91928222e-03  7.00813505e-03  7.09698787e-03
   7.18584069e-03  7.27469352e-03  7.

Y me costó 215.000000 microsegundos calcularlo 

Intento  #1
Timestamps:  [[2, 95], [3, 209], [4, 219], [5, 249], [6, 256], [7, 268], [8, 268]]
Antes de line_similarity 2025-05-18 17:23:44.455345
Despues de line_similarity: 2025-05-18 17:23:44.455635
La distancia al cuadrado entre l1 y l2 es: 26949.326406250195
Y me costó 290.000000 microsegundos calcularlo 

Step 2:ordered_lines_by_intersection
Step 3:Compute Homography
Projected Lines Antes: [[-8.37925400e-04 -8.26904516e-04 -8.15883632e-04 -8.04862748e-04
  -7.93841864e-04 -7.82820981e-04 -7.71800097e-04 -7.60779213e-04
  -7.49758329e-04 -7.38737445e-04 -7.27716561e-04  3.53308801e-03
   3.54410889e-03  3.55512978e-03  3.56615066e-03  3.57717154e-03
   3.58819243e-03  3.59921331e-03  3.61023420e-03  3.62125508e-03
   3.63227596e-03  3.64329685e-03]
 [-8.56306822e-02 -6.27116586e-02 -3.97926350e-02 -1.68736113e-02
   6.04541232e-03  2.89644360e-02  5.18834596e-02  7.48024832e-02
   9.77215069e-02  1.20640531e-01  1.43559554e-01 -8.52

Projected Lines Despues: [[ 1.98865018e-04  2.17341495e-04  2.38699638e-04  2.63670618e-04
   2.93255826e-04  3.28864406e-04  3.72544316e-04  4.27390602e-04
   4.98312656e-04  5.93592016e-04  7.28377906e-04  6.73810829e-05
   1.35722660e-04  3.72120021e-04  1.92407048e-03  3.50338559e-04
   2.15982275e-04  1.65949589e-04  1.39817779e-04  1.23762472e-04
   1.12897445e-04  1.05056074e-04]
 [-1.79375672e-03 -1.80516219e-03 -1.81834649e-03 -1.83376099e-03
  -1.85202383e-03 -1.87400487e-03 -1.90096832e-03 -1.93482471e-03
  -1.97860461e-03 -2.03742015e-03 -2.12062287e-03 -2.06839004e-03
  -2.30679055e-03 -3.13143046e-03 -4.87857365e-03  6.11228116e-04
   1.07991341e-03  1.25444614e-03  1.34560365e-03  1.40161055e-03
   1.43951181e-03  1.46686543e-03]
 [ 9.99998371e-01  9.99998347e-01  9.99998318e-01  9.99998284e-01
   9.99998242e-01  9.99998190e-01  9.99998124e-01  9.99998037e-01
   9.99997918e-01  9.99997748e-01  9.99997486e-01  9.99997859e-01
   9.99997330e-01  9.99995028e-01 -9.99986249e-

Despues de line_similarity: 2025-05-18 17:23:45.305896
La distancia al cuadrado entre l1 y l2 es: 3690957.730795783
Y me costó 526.000000 microsegundos calcularlo 

Step 1.2: Select lines from VP2
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 207], [3, 386], [4, 404], [5, 469], [6, 487], [7, 510], [8, 512]]
Antes de line_similarity 2025-05-18 17:23:45.307701
Despues de line_similarity: 2025-05-18 17:23:45.308259
La distancia al cuadrado entre l1 y l2 es: 8.013387213717774
Y me costó 558.000000 microsegundos calcularlo 

Intento  #1
Timestamps:  [[2, 256], [3, 411], [4, 427], [5, 485], [6, 501], [7, 522], [8, 523]]
Antes de line_similarity 2025-05-18 17:23:45.309278
Despues de line_similarity: 2025-05-18 17:23:45.309848
La distancia al cuadrado entre l1 y l2 es: 145.50390625001646
Y me costó 570.000000 microsegundos calcularlo 

Intento  #2
Timestamps:  [[2, 244], [3, 402], [4, 422], [5, 474], [6, 488], [7, 507], [8, 509]]
Antes de line_similarity 2025-05-18 17:23:45.310851
D

Step 2:ordered_lines_by_intersection
Step 3:Compute Homography
Projected Lines Antes: [[ 1.35172606e-02  1.37210890e-02  1.39249173e-02  1.41287457e-02
   1.43325741e-02  1.45364025e-02  1.47402309e-02  1.49440593e-02
   1.51478877e-02  1.53517160e-02  1.55555444e-02 -3.04849432e-03
  -2.84466593e-03 -2.64083755e-03 -2.43700916e-03 -2.23318078e-03
  -2.02935239e-03 -1.82552401e-03 -1.62169562e-03 -1.41786724e-03
  -1.21403885e-03 -1.01021047e-03]
 [-1.21240716e-01 -1.13559470e-01 -1.05878224e-01 -9.81969778e-02
  -9.05157317e-02 -8.28344855e-02 -7.51532393e-02 -6.74719932e-02
  -5.97907470e-02 -5.21095008e-02 -4.44282547e-02 -4.89237993e-02
  -4.12425532e-02 -3.35613070e-02 -2.58800608e-02 -1.81988147e-02
  -1.05175685e-02 -2.83632234e-03  4.84492383e-03  1.25261700e-02
   2.02074162e-02  2.78886623e-02]
 [ 6.75622076e+01  6.28901230e+01  5.82180383e+01  5.35459537e+01
   4.88738691e+01  4.42017845e+01  3.95296999e+01  3.48576152e+01
   3.01855306e+01  2.55134460e+01  2.08413614e+01  3

Projected Lines Despues: [[-2.63862572e-04 -2.62863767e-04 -2.61925225e-04 -2.61041651e-04
  -2.60208354e-04 -2.59421162e-04 -2.58676350e-04 -2.57970587e-04
  -2.57300879e-04 -2.56664533e-04 -2.56059116e-04  6.01708291e-03
   3.07012340e-03  1.05278423e-03  5.65610441e-04  3.46355968e-04
   2.21674828e-04  1.41232728e-04  8.50322301e-05  4.35502705e-05
   1.16742922e-05 -1.35861427e-05]
 [ 1.74065279e-03  1.77019952e-03  1.79796355e-03  1.82410149e-03
   1.84875213e-03  1.87203891e-03  1.89407196e-03  1.91494989e-03
   1.93476121e-03  1.95358561e-03  1.97149506e-03 -2.33760840e-02
  -9.11577757e-03 -1.90247503e-03 -1.60526835e-04  6.23441794e-04
   1.06925245e-03  1.35688152e-03  1.55783212e-03  1.70615504e-03
   1.82013078e-03  1.91045196e-03]
 [-9.99998450e-01 -9.99998399e-01 -9.99998349e-01 -9.99998302e-01
  -9.99998257e-01 -9.99998214e-01 -9.99998173e-01 -9.99998133e-01
  -9.99998095e-01 -9.99998059e-01 -9.99998024e-01  9.99708634e-01
  -9.99953737e-01 -9.99997636e-01 -9.99999827e-

Step 4: Compara Lineas
projected_lines.shape =  (3, 22)
len(lines_near_vps)   =  37
Se requirieron  759  iteraciones para buscar similitudes.
Iteracion:  55
Step 1.1: Select lines from VP1
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 103], [3, 181], [4, 193], [5, 234], [6, 247], [7, 261], [8, 261]]
Antes de line_similarity 2025-05-18 17:23:46.625517
Despues de line_similarity: 2025-05-18 17:23:46.625806
La distancia al cuadrado entre l1 y l2 es: 3702283.9732230464
Y me costó 289.000000 microsegundos calcularlo 

Step 1.2: Select lines from VP2
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 202], [3, 370], [4, 388], [5, 450], [6, 481], [7, 510], [8, 511]]
Antes de line_similarity 2025-05-18 17:23:46.628563
Despues de line_similarity: 2025-05-18 17:23:46.629329
La distancia al cuadrado entre l1 y l2 es: 891.8697107863429
Y me costó 766.000000 microsegundos calcularlo 

Intento  #1
Timestamps:  [[2, 213], [3, 395], [4, 416], [5, 482], [6, 912], [7, 937], [8, 939]]
An

Y me costó 641.000000 microsegundos calcularlo 

Step 2:ordered_lines_by_intersection
Step 3:Compute Homography
Projected Lines Antes: [[-8.42398350e-04 -8.39136659e-04 -8.35874967e-04 -8.32613275e-04
  -8.29351583e-04 -8.26089891e-04 -8.22828199e-04 -8.19566507e-04
  -8.16304816e-04 -8.13043124e-04 -8.09781432e-04  2.67096309e-03
   2.67422478e-03  2.67748647e-03  2.68074816e-03  2.68400985e-03
   2.68727155e-03  2.69053324e-03  2.69379493e-03  2.69705662e-03
   2.70031831e-03  2.70358000e-03]
 [-9.60733919e-02 -7.07456250e-02 -4.54178581e-02 -2.00900913e-02
   5.23767557e-03  3.05654424e-02  5.58932093e-02  8.12209761e-02
   1.06548743e-01  1.31876510e-01  1.57204277e-01 -9.56318573e-02
  -7.03040905e-02 -4.49763236e-02 -1.96485568e-02  5.67921008e-03
   3.10069769e-02  5.63347438e-02  8.16625107e-02  1.06990278e-01
   1.32318044e-01  1.57645811e-01]
 [ 5.20627304e+01  3.83400285e+01  2.46173267e+01  1.08946248e+01
  -2.82807708e+00 -1.65507789e+01 -3.02734808e+01 -4.39961827e+01
  -

Projected Lines Despues: [[ 1.76179849e-04  1.89722902e-04  2.04855707e-04  2.21875640e-04
   2.41159171e-04  2.63190049e-04  2.88600431e-04  3.18232530e-04
   3.53233768e-04  3.95208797e-04  4.46472457e-04  4.74229911e-04
   4.32378000e-04  3.98346120e-04  3.70129781e-04  3.46355643e-04
   3.26051227e-04  3.08508610e-04  2.93200186e-04  2.79724693e-04
   2.67771531e-04  2.57096525e-04]
 [-1.78564449e-03 -1.79624909e-03 -1.80809851e-03 -1.82142561e-03
  -1.83652517e-03 -1.85377598e-03 -1.87367303e-03 -1.89687581e-03
  -1.92428278e-03 -1.95715041e-03 -1.99729130e-03  1.77236286e-04
   3.23274953e-04  4.42026261e-04  5.40484718e-04  6.23442489e-04
   6.94292955e-04  7.55506361e-04  8.08923744e-04  8.55945272e-04
   8.97654758e-04  9.34904230e-04]
 [ 9.99998390e-01  9.99998369e-01  9.99998344e-01  9.99998317e-01
   9.99998285e-01  9.99998247e-01  9.99998203e-01  9.99998150e-01
   9.99998086e-01  9.99998007e-01  9.99997906e-01 -9.99999872e-01
  -9.99999854e-01 -9.99999823e-01 -9.99999785e-

len(lines_near_vps)   =  37
Se requirieron  752  iteraciones para buscar similitudes.
Iteracion:  62
Step 1.1: Select lines from VP1
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 209], [3, 381], [4, 401], [5, 466], [6, 487], [7, 517], [8, 519]]
Antes de line_similarity 2025-05-18 17:23:47.752147
Despues de line_similarity: 2025-05-18 17:23:47.752704
La distancia al cuadrado entre l1 y l2 es: 3702509.1311227544
Y me costó 557.000000 microsegundos calcularlo 

Step 1.2: Select lines from VP2
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 292], [3, 454], [4, 471], [5, 532], [6, 549], [7, 576], [8, 578]]
Antes de line_similarity 2025-05-18 17:23:47.754201
Despues de line_similarity: 2025-05-18 17:23:47.754831
La distancia al cuadrado entre l1 y l2 es: 608814.3031796023
Y me costó 630.000000 microsegundos calcularlo 

Step 2:ordered_lines_by_intersection
Step 3:Compute Homography
Projected Lines Antes: [[ 6.46162843e-03  6.56459436e-03  6.66756030e-03  6.77052623e-03
  

Projected Lines Despues: [[-2.41338628e-04 -2.44873240e-04 -2.48448101e-04 -2.52063904e-04
  -2.55721355e-04 -2.59421177e-04 -2.63164113e-04 -2.66950919e-04
  -2.70782371e-04 -2.74659265e-04 -2.78582412e-04  3.74067954e-04
   3.71945370e-04  3.68499006e-04  3.61929303e-04  3.44472220e-04
   1.58223222e-04 -4.41616479e-04 -4.08925933e-04 -3.99643019e-04
  -3.95254669e-04 -3.92697410e-04]
 [ 1.83311075e-03  1.84072006e-03  1.84841601e-03  1.85620011e-03
   1.86407386e-03  1.87203883e-03  1.88009662e-03  1.88824885e-03
   1.89649719e-03  1.90484336e-03  1.91328910e-03  5.20680734e-04
   5.28202019e-04  5.40414071e-04  5.63693540e-04  6.25551983e-04
   1.28551704e-03 -2.81325266e-04 -3.97162909e-04 -4.30056539e-04
  -4.45606479e-04 -4.54668021e-04]
 [-9.99998291e-01 -9.99998276e-01 -9.99998261e-01 -9.99998245e-01
  -9.99998230e-01 -9.99998214e-01 -9.99998198e-01 -9.99998182e-01
  -9.99998165e-01 -9.99998148e-01 -9.99998131e-01 -9.99999794e-01
  -9.99999791e-01 -9.99999786e-01 -9.99999776e-

Projected Lines Despues: [[ 1.12361443e-04  1.38046032e-04  1.69546869e-04  2.09091830e-04
   2.60213164e-04  3.28865783e-04  4.25934147e-04  5.73664321e-04
   8.25723201e-04  1.35295322e-03  3.14753358e-03  1.59468406e-04
   1.59139828e-04  1.58822250e-04  1.58515131e-04  1.58217962e-04
   1.57930266e-04  1.57651599e-04  1.57381541e-04  1.57119700e-04
   1.56865706e-04  1.56619212e-04]
 [-1.79438384e-03 -1.80382974e-03 -1.81541465e-03 -1.82995790e-03
  -1.84875854e-03 -1.87400655e-03 -1.90970487e-03 -1.96403476e-03
  -2.05673295e-03 -2.25062876e-03 -2.91060529e-03  1.25670330e-03
   1.26427660e-03  1.27159632e-03  1.27867501e-03  1.28552437e-03
   1.29215536e-03  1.29857827e-03  1.30480274e-03  1.31083782e-03
   1.31669204e-03  1.32237339e-03]
 [ 9.99998384e-01  9.99998364e-01  9.99998338e-01  9.99998304e-01
   9.99998257e-01  9.99998190e-01  9.99998086e-01  9.99997907e-01
   9.99997544e-01  9.99996552e-01  9.99990811e-01 -9.99999198e-01
  -9.99999188e-01 -9.99999179e-01 -9.99999170e-

Despues de line_similarity: 2025-05-18 17:23:49.062559
La distancia al cuadrado entre l1 y l2 es: 8.013387213717774
Y me costó 662.000000 microsegundos calcularlo 

Intento  #1
Timestamps:  [[2, 174], [3, 329], [4, 343], [5, 398], [6, 413], [7, 434], [8, 435]]
Antes de line_similarity 2025-05-18 17:23:49.063666
Despues de line_similarity: 2025-05-18 17:23:49.064148
La distancia al cuadrado entre l1 y l2 es: 891.8697107863429
Y me costó 482.000000 microsegundos calcularlo 

Intento  #2
Timestamps:  [[2, 199], [3, 367], [4, 388], [5, 455], [6, 474], [7, 498], [8, 500]]
Antes de line_similarity 2025-05-18 17:23:49.065448
Despues de line_similarity: 2025-05-18 17:23:49.066003
La distancia al cuadrado entre l1 y l2 es: 906947.3087351547
Y me costó 555.000000 microsegundos calcularlo 

Step 2:ordered_lines_by_intersection
Step 3:Compute Homography
Projected Lines Antes: [[-5.94370357e-03 -6.10173672e-03 -6.25976988e-03 -6.41780303e-03
  -6.57583618e-03 -6.73386934e-03 -6.89190249e-03 -7.0499

Projected Lines Despues: [[-3.03870432e-05 -3.82069469e-05 -5.52804976e-05 -1.21833735e-04
  -2.41160055e-04 -4.99125493e-05 -2.42561611e-05 -1.41027014e-05
  -8.66095899e-06 -5.26888482e-06 -2.95197408e-06  2.55110928e-04
   4.79322324e-04  3.20126919e-03  7.11857240e-04  3.25968223e-04
   2.13711830e-04  1.60220917e-04  1.28923163e-04  1.08379752e-04
   9.38603728e-05  8.30541590e-05]
 [-1.85106367e-03 -1.85148229e-03 -1.85239628e-03 -1.85595902e-03
   1.83652702e-03  1.84676503e-03  1.84813848e-03  1.84868202e-03
   1.84897333e-03  1.84915492e-03  1.84927895e-03 -2.81902278e-03
  -3.64061530e-03 -1.36147148e-02 -7.24317767e-04  6.89729969e-04
   1.10108038e-03  1.29709144e-03  1.41177829e-03  1.48705713e-03
   1.54026163e-03  1.57985968e-03]
 [ 9.99998286e-01  9.99998285e-01  9.99998283e-01  9.99998270e-01
  -9.99998285e-01 -9.99998293e-01 -9.99998292e-01 -9.99998291e-01
  -9.99998291e-01 -9.99998290e-01 -9.99998290e-01  9.99995994e-01
   9.99993258e-01  9.99902191e-01 -9.99999484e-

Despues de line_similarity: 2025-05-18 17:23:49.946109
La distancia al cuadrado entre l1 y l2 es: 657132.0896697482
Y me costó 609.000000 microsegundos calcularlo 

Step 2:ordered_lines_by_intersection
Step 3:Compute Homography
Projected Lines Antes: [[-1.43902096e-02 -1.46992586e-02 -1.50083076e-02 -1.53173566e-02
  -1.56264056e-02 -1.59354546e-02 -1.62445035e-02 -1.65535525e-02
  -1.68626015e-02 -1.71716505e-02 -1.74806995e-02  3.32989533e-03
   3.02084633e-03  2.71179734e-03  2.40274835e-03  2.09369936e-03
   1.78465036e-03  1.47560137e-03  1.16655238e-03  8.57503385e-04
   5.48454393e-04  2.39405400e-04]
 [ 9.03465061e-02  9.52759469e-02  1.00205388e-01  1.05134828e-01
   1.10064269e-01  1.14993710e-01  1.19923151e-01  1.24852592e-01
   1.29782033e-01  1.34711473e-01  1.39640914e-01 -1.53978717e-02
  -1.04684309e-02 -5.53899009e-03 -6.09549285e-04  4.31989152e-03
   9.24933233e-03  1.41787731e-02  1.91082139e-02  2.40376547e-02
   2.89670956e-02  3.38965364e-02]
 [-5.11568461e+01 -

Projected Lines Despues: [[-1.12924874e-05 -1.64975518e-05 -2.74649132e-05 -6.56265425e-05
  -2.90838168e-04 -4.99125668e-05 -2.86686451e-05 -2.07295892e-05
  -1.65769805e-05 -1.40235567e-05 -1.22946950e-05  1.07513124e-04
   1.67607603e-04  3.91472030e-04  1.06713875e-03  2.21674414e-04
   1.22389674e-04  8.39018139e-05  6.34574804e-05  5.07776347e-05
   4.21449061e-05  3.58883390e-05]
 [-1.84626366e-03 -1.84622103e-03 -1.84613120e-03 -1.84581863e-03
   1.84873823e-03  1.84676497e-03  1.84659097e-03  1.84652594e-03
   1.84649193e-03  1.84647102e-03  1.84645686e-03 -2.20628589e-03
  -2.41385541e-03 -3.18709430e-03 -1.85104141e-03  1.06925309e-03
   1.41218859e-03  1.54512793e-03  1.61574385e-03  1.65954077e-03
   1.68935871e-03  1.71096925e-03]
 [ 9.99998296e-01  9.99998296e-01  9.99998296e-01  9.99998294e-01
  -9.99998249e-01 -9.99998293e-01 -9.99998295e-01 -9.99998295e-01
  -9.99998295e-01 -9.99998295e-01 -9.99998295e-01  9.99997560e-01
   9.99997073e-01  9.99994845e-01 -9.99997717e-

len(lines_near_vps)   =  37
Se requirieron  766  iteraciones para buscar similitudes.
Iteracion:  79
Step 1.1: Select lines from VP1
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 89], [3, 153], [4, 163], [5, 193], [6, 201], [7, 221], [8, 222]]
Antes de line_similarity 2025-05-18 17:23:50.813114
Despues de line_similarity: 2025-05-18 17:23:50.813425
La distancia al cuadrado entre l1 y l2 es: 3690957.730795783
Y me costó 311.000000 microsegundos calcularlo 

Step 1.2: Select lines from VP2
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 81], [3, 146], [4, 155], [5, 182], [6, 189], [7, 200], [8, 201]]
Antes de line_similarity 2025-05-18 17:23:50.814306
Despues de line_similarity: 2025-05-18 17:23:50.814525
La distancia al cuadrado entre l1 y l2 es: 961293.9297776863
Y me costó 219.000000 microsegundos calcularlo 

Step 2:ordered_lines_by_intersection
Step 3:Compute Homography
Projected Lines Antes: [[ 7.44457044e-03  7.60406525e-03  7.76356007e-03  7.92305488e-03
   8.

Projected Lines Despues: [[-2.67859417e-03 -2.12488824e-03 -7.57063102e-04 -4.59223720e-04
  -3.28864355e-04 -2.55721367e-04 -2.08904360e-04 -1.76367982e-04
  -1.52442853e-04 -1.34109854e-04 -1.19613529e-04  3.45660322e-05
   4.96182855e-05  8.35977962e-05  2.32657276e-04  3.46356237e-04
   1.03761185e-04  6.25346585e-05  4.54917198e-05  3.61789461e-05
   3.03093140e-05  2.62712338e-05]
 [-1.46566296e-03  2.11785432e-03  1.93214266e-03  1.89170410e-03
   1.87400476e-03  1.86407387e-03  1.85771735e-03  1.85329976e-03
   1.85005135e-03  1.84756221e-03  1.84559399e-03 -1.96620544e-03
  -2.01926508e-03 -2.13904385e-03 -2.66448253e-03  6.23441227e-04
   1.47859762e-03  1.62392248e-03  1.68399939e-03  1.71682721e-03
   1.73751785e-03  1.75175221e-03]
 [ 9.99995338e-01 -9.99995500e-01 -9.99997847e-01 -9.99998105e-01
  -9.99998190e-01 -9.99998230e-01 -9.99998253e-01 -9.99998267e-01
  -9.99998277e-01 -9.99998284e-01 -9.99998290e-01  9.99998066e-01
   9.99997960e-01  9.99997709e-01  9.99996423e-

Despues de line_similarity: 2025-05-18 17:23:51.689642
La distancia al cuadrado entre l1 y l2 es: 24672.080950085485
Y me costó 1007.000000 microsegundos calcularlo 

Step 2:ordered_lines_by_intersection
Step 3:Compute Homography
Projected Lines Antes: [[-4.73073057e-04 -5.48114507e-04 -6.23155957e-04 -6.98197407e-04
  -7.73238857e-04 -8.48280307e-04 -9.23321757e-04 -9.98363207e-04
  -1.07340466e-03 -1.14844611e-03 -1.22348756e-03  4.62772502e-03
   4.55268357e-03  4.47764212e-03  4.40260067e-03  4.32755922e-03
   4.25251777e-03  4.17747632e-03  4.10243487e-03  4.02739342e-03
   3.95235197e-03  3.87731052e-03]
 [-9.61034144e-02 -7.06054327e-02 -4.51074510e-02 -1.96094693e-02
   5.88851237e-03  3.13864941e-02  5.68844758e-02  8.23824575e-02
   1.07880439e-01  1.33378421e-01  1.58876403e-01 -9.28350609e-02
  -6.73370792e-02 -4.18390975e-02 -1.63411158e-02  9.15686587e-03
   3.46548476e-02  6.01528293e-02  8.56508110e-02  1.11148793e-01
   1.36646774e-01  1.62144756e-01]
 [ 5.19498464e+01

Projected Lines Despues: [[-5.50351896e-04 -4.49902432e-04 -3.80495481e-04 -3.29667068e-04
  -2.90838183e-04 -2.60208194e-04 -2.35428238e-04 -2.14968457e-04
  -1.97789660e-04 -1.83161210e-04 -1.70554418e-04  4.27366328e-05
   5.91117894e-05  9.64011908e-05  2.65470727e-04  3.44462060e-04
   1.03761270e-04  6.08370846e-05  4.29119366e-05  3.30719835e-05
   2.68536101e-05  2.25681893e-05]
 [ 1.84862286e-03  1.84866757e-03  1.84869844e-03  1.84872105e-03
   1.84873831e-03  1.84875193e-03  1.84876295e-03  1.84877204e-03
   1.84877968e-03  1.84878618e-03  1.84879178e-03 -1.99777388e-03
  -2.05580602e-03 -2.18795643e-03 -2.78712377e-03  6.25573059e-04
   1.47859761e-03  1.63071738e-03  1.69424260e-03  1.72911457e-03
   1.75115197e-03  1.76633914e-03]
 [-9.99998140e-01 -9.99998190e-01 -9.99998219e-01 -9.99998237e-01
  -9.99998249e-01 -9.99998257e-01 -9.99998263e-01 -9.99998268e-01
  -9.99998271e-01 -9.99998274e-01 -9.99998276e-01  9.99998004e-01
   9.99997885e-01  9.99997602e-01  9.99996081e-

Step 4: Compara Lineas
projected_lines.shape =  (3, 22)
len(lines_near_vps)   =  37
Se requirieron  761  iteraciones para buscar similitudes.
Iteracion:  89
Step 1.1: Select lines from VP1
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 152], [3, 250], [4, 269], [5, 316], [6, 335], [7, 357], [8, 358]]
Antes de line_similarity 2025-05-18 17:23:52.617057
Despues de line_similarity: 2025-05-18 17:23:52.617455
La distancia al cuadrado entre l1 y l2 es: 3702509.1311227544
Y me costó 398.000000 microsegundos calcularlo 

Step 1.2: Select lines from VP2
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 148], [3, 251], [4, 273], [5, 329], [6, 373], [7, 450], [8, 455]]
Antes de line_similarity 2025-05-18 17:23:52.619090
Despues de line_similarity: 2025-05-18 17:23:52.619623
La distancia al cuadrado entre l1 y l2 es: 158.42682546954876
Y me costó 533.000000 microsegundos calcularlo 

Intento  #1
Timestamps:  [[2, 277], [3, 461], [4, 492], [5, 584], [6, 664], [7, 701], [8, 703]]
A

Step 4: Compara Lineas
projected_lines.shape =  (3, 22)
len(lines_near_vps)   =  37
Se requirieron  741  iteraciones para buscar similitudes.
Iteracion:  91
Step 1.1: Select lines from VP1
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 362], [3, 566], [4, 590], [5, 667], [6, 952], [7, 1001], [8, 1003]]
Antes de line_similarity 2025-05-18 17:23:52.971344
Despues de line_similarity: 2025-05-18 17:23:52.972404
La distancia al cuadrado entre l1 y l2 es: 3690957.730795783
Y me costó 1060.000000 microsegundos calcularlo 

Step 1.2: Select lines from VP2
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 209], [3, 377], [4, 394], [5, 465], [6, 521], [7, 554], [8, 555]]
Antes de line_similarity 2025-05-18 17:23:52.974883
Despues de line_similarity: 2025-05-18 17:23:52.975501
La distancia al cuadrado entre l1 y l2 es: 906947.3087351547
Y me costó 618.000000 microsegundos calcularlo 

Step 2:ordered_lines_by_intersection
Step 3:Compute Homography
Projected Lines Antes: [[-2.03609

Projected Lines Despues: [[-1.26580233e-05 -1.79935184e-05 -2.92430330e-05 -6.84640668e-05
  -2.93255561e-04 -4.99133132e-05 -2.82300663e-05 -2.01173169e-05
  -1.58717914e-05 -1.32605290e-05 -1.14922014e-05  4.02646511e-04
   1.33540690e-03  1.00007499e-03  3.61945976e-04  2.20258745e-04
   1.57930154e-04  1.22874029e-04  1.00403560e-04  8.47725762e-05
   7.32708711e-05  6.44530922e-05]
 [-1.84541539e-03 -1.84530014e-03 -1.84505713e-03 -1.84420988e-03
   1.85202358e-03  1.84676704e-03  1.84629865e-03  1.84612340e-03
   1.84603169e-03  1.84597528e-03  1.84593708e-03 -3.22884750e-03
  -6.45135115e-03 -1.61731826e-03  5.87315456e-04  1.07682087e-03
   1.29215546e-03  1.41326831e-03  1.49089989e-03  1.54490222e-03
   1.58463861e-03  1.61510250e-03]
 [ 9.99998297e-01  9.99998297e-01  9.99998297e-01  9.99998297e-01
  -9.99998242e-01 -9.99998293e-01 -9.99998295e-01 -9.99998296e-01
  -9.99998296e-01 -9.99998296e-01 -9.99998296e-01  9.99994706e-01
   9.99978298e-01 -9.99998192e-01 -9.99999762e-

Despues de line_similarity: 2025-05-18 17:23:53.986498
La distancia al cuadrado entre l1 y l2 es: 3695253.712582726
Y me costó 706.000000 microsegundos calcularlo 

Step 1.2: Select lines from VP2
Select_Lines_with_distance
Intento  #0
Timestamps:  [[2, 302], [3, 388], [4, 406], [5, 454], [6, 468], [7, 485], [8, 485]]
Antes de line_similarity 2025-05-18 17:23:53.989238
Despues de line_similarity: 2025-05-18 17:23:53.990019
La distancia al cuadrado entre l1 y l2 es: 1.2924697071141057e-26
Y me costó 781.000000 microsegundos calcularlo 

Intento  #1
Timestamps:  [[2, 103], [3, 177], [4, 190], [5, 231], [6, 240], [7, 592], [8, 593]]
Antes de line_similarity 2025-05-18 17:23:53.991551
Despues de line_similarity: 2025-05-18 17:23:53.992170
La distancia al cuadrado entre l1 y l2 es: 160.50881404290877
Y me costó 619.000000 microsegundos calcularlo 

Intento  #2
Timestamps:  [[2, 93], [3, 166], [4, 175], [5, 205], [6, 213], [7, 226], [8, 227]]
Antes de line_similarity 2025-05-18 17:23:53.9934

Projected Lines Despues: [[ 1.07511540e-04  1.26760148e-04  1.52343582e-04  1.88005037e-04
   2.41160135e-04  3.28864333e-04  5.01018208e-04  9.92840899e-04
   1.42451099e-02  1.22088896e-03  6.00908429e-04  1.41521730e-04
   2.47633354e-04  7.04936887e-04  1.14906913e-03  3.46356397e-04
   2.13767726e-04  1.59270902e-04  1.29569535e-04  1.10877421e-04
   9.80305104e-05  8.86577522e-05]
 [-1.77941672e-03 -1.78764200e-03 -1.79857426e-03 -1.81381304e-03
  -1.83652716e-03 -1.87400472e-03 -1.94756907e-03 -2.15773314e-03
  -7.82046299e-03  1.21176538e-03  1.47669555e-03 -2.30952664e-03
  -2.67624308e-03 -4.25665808e-03 -2.15071176e-03  6.23440932e-04
   1.08166220e-03  1.27000098e-03  1.37264764e-03  1.43724679e-03
   1.48164516e-03  1.51403700e-03]
 [ 9.99998411e-01  9.99998394e-01  9.99998371e-01  9.99998337e-01
   9.99998285e-01  9.99998190e-01  9.99997978e-01  9.99997179e-01
   9.99867950e-01 -9.99998521e-01 -9.99998729e-01  9.99997323e-01
   9.99996388e-01  9.99990692e-01 -9.99997027e-

In [22]:
# Print the top 5 results
for i, (similarities, d, M, it) in enumerate(best_results[:5]):
    print(f"Rank {i+1}: Similarities = {similarities}")
    print("Dist promedio: ", d)
    print("Iteracion: ", it)
    print("Matrix M:")
    print(M)

Rank 1: Similarities = 5
Dist promedio:  0.5579095011740847
Iteracion:  14
Matrix M:
[[ 1.41643214e+03 -1.00333053e+01  6.80901794e+02]
 [ 6.57958347e+02 -2.90491365e+00  6.28533203e+02]
 [ 8.64272559e-01 -5.33630074e-03  1.00000000e+00]]
Rank 2: Similarities = 5
Dist promedio:  0.40679242298268353
Iteracion:  39
Matrix M:
[[1.21178053e+02 3.82584352e+00 1.49839868e+03]
 [8.91512299e+01 1.11834594e+00 7.77210510e+02]
 [1.29574260e-01 2.02390419e-03 1.00000000e+00]]
Rank 3: Similarities = 5
Dist promedio:  0.9229356296834104
Iteracion:  42
Matrix M:
[[ 4.69248793e+03 -2.48322374e+00  9.12593811e+02]
 [ 2.78498477e+03 -6.97063186e-01  6.69004028e+02]
 [ 3.92772894e+00 -1.28276085e-03  1.00000000e+00]]
Rank 4: Similarities = 5
Dist promedio:  0.4591860003041178
Iteracion:  46
Matrix M:
[[ 1.99538823e+00 -1.25596805e+03  1.57494739e+03]
 [-3.72712186e+01 -3.52850372e+02  5.84052612e+02]
 [-6.89309284e-02 -6.52315332e-01  1.00000000e+00]]
Rank 5: Similarities = 5
Dist promedio:  0.407579405

In [23]:
for i, (similarities, d, M, it) in enumerate(best_results[:5]):
    img = cv2.imread('vp.jpg')
    lines = def_grid_lines(-5,5,-5,5,1,1)
    Hl = np.linalg.inv(M).T
    projected_lines = np.dot(Hl, lines)
    projected_lines = projected_lines / np.linalg.norm(projected_lines, axis=0)
    # Dibujar líneas proyectadas
    for i in range(projected_lines.shape[1]):
        a, b, c = projected_lines[:, i]
        # Encontrar dos puntos en la línea (para dibujar)
        x0, y0 = 0, int(-c/b) if b != 0 else 0
        x1, y1 = img.shape[1], int((-c - a*img.shape[1])/b) if b != 0 else 0
        cv2.line(img, (x0, y0), (x1, y1), (255, 0, 0), 2)

    cv2.namedWindow("Projected Grid", cv2.WINDOW_NORMAL)
    cv2.imshow("Projected Grid", img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()